### ISSUE TITLE
Tami4 integration stopped working

### ISSUE THREAD

**Issue by NiiiYaa** [Guy293/Tami4EdgeAPI#7]
First the 'boiled water' button stopped working (once clicked it generated an error). 
After few failed attempts I wanted to 're-install', the I deleted the integration and tried to install.
On the validation/verification process (SMS) -  after inputting the mobile number - "Unexpected error" is received (screenshot below).
![2024-06-04 08_12_14-Settings – Home Assistant](https://github.com/Guy293/Tami4EdgeAPI/assets/113662601/6220d8ce-f988-403e-9af8-ce10683c375e)

 
Here is the log:
Logger: homeassistant.components.tami4.config_flow
Source: components/tami4/config_flow.py:46
integration: Tami4 Edge / Edge+ (documentation, issues)
First occurred: 8:08:17 AM (9 occurrences)
Last logged: 10:53:03 AM

Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/tami4/config_flow.py", line 46, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/Tami4EdgeAPI/Tami4EdgeAPI.py", line 215, in request_otp
    if not response["success"]:
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'success'

**Comment by Guy293** [comment]
Hi, by looking at the logs attached in: https://github.com/home-assistant/core/issues/113167#issuecomment-2146682339
Looks like they changed the API.
I will fix it soon.

**Comment by michaelrodov** [comment]
@Guy293 thanks guy
was about to post here, but saw that you responded already.

**Comment by shaikedem** [comment]
following

**Comment by danielrubin1989** [comment]
Thanks @Guy293 , Great integration 👍 following..

**Comment by Guy293** [comment]
I've released an update for Tami4EdgeAPI, version v3.0.
I am now working on pushing it to Home Assistant repo.

**Comment by michaelrodov** [comment]
> I've released an update for Tami4EdgeAPI, version v3.0. I am now working on pushing it to Home Assistant repo.

thank you Guy! 
אין עליך!

**Comment by Guy293** [comment]
I've opened a PR In home assistant, Y'all can help merging it faster by reviewing it and adding a comment: https://github.com/home-assistant/core/pull/119158

**Comment by michaelrodov** [comment]
@Guy293 which version of HA it will be released on? thought its part of 2024.6.2?

**Comment by shaikedem** [comment]
any update on this? its stiull not working ...

**Comment by Guy293** [comment]
> any update on this? its stiull not working ...

Seems like the latest home assistant version includes the fix

**Comment by orenc75** [comment]
Hi Guy, I updated to the latest hass version and still encounter a problem. I get "Unknown error occurred" once I enter the code I get via SMS.
![image](https://github.com/Guy293/Tami4EdgeAPI/assets/12273488/399ce3a8-8a59-41d2-b813-3193e366768f)

I am sure my phone number is registered since I am using the Tami4 app and I am sure I write the correct code into hass...

Here is the log:
Logger: root
Source: /usr/local/lib/python3.12/site-packages/Tami4EdgeAPI/Tami4EdgeAPI.py:251
First occurred: July 3, 2024 at 9:45:08 PM (3 occurrences)
Last logged: 7:39:21 AM

OTP Submission Failed, response: {'status': 403, 'message': 'invalid_grant', 'description': 'Wrong phone number or verification code.', 'timestamp': '2024-07-03T18:45:08Z'}
OTP Submission Failed, response: {'status': 403, 'message': 'invalid_grant', 'description': 'Wrong phone number or verification code.', 'timestamp': '2024-07-03T18:45:44Z'}
OTP Submission Failed, response: {'status': 403, 'message': 'invalid_grant', 'description': 'Wrong phone number or verification code.', 'timestamp': '2024-07-04T04:39:21Z'}
